#!/bin/bash

# Janusz Ładecki <szunaj13pl@gmail.com>
# 21.09.2017


# Parameters
# GITLAB_URL=""
# GITLAB_PRIVATE_TOKEN=""
PROJECT_SEARCH_PARAM=$1


function initial(){
    
    local scriptName=$(basename $0)
    gitlabScript=$(mktemp /tmp/$scriptName.XXXXXX)
    gitlabNames=$(mktemp /tmp/$scriptName.XXXXXX)
    gitlabGit=$(mktemp /tmp/$scriptName.XXXXXX)
    
    # Colors
    RED='\033[0;31m'
    NC='\033[0m' # No Color
}


function isInstalled(){
    
    local packagesName=$@
    
    for package in $packagesName; do
        INSTALLED=$(dpkg-query -s "$package" 2>&1 | grep --no-messages Status )
        if [ "$INSTALLED" != "Status: install ok installed" ]; then
            echo -e "${NC} $packageName ${RED}not installed ${NC}"
            sudo apt install -y "$packageName"
        fi
    done
    
}


function preRunCheck(){
    
    if [ -z "$GITLAB_URL" ]; then
        echo -e "${RED}Please set the environment variable GITLAB_URL ${NC}"
        exit 1
    fi
    
    if [ -z "$GITLAB_PRIVATE_TOKEN" ]; then
        echo -e "${RED}Please set the environment variable GITLAB_PRIVATE_TOKEN ${NC}"
        echo "See ${GITLAB_URL}/profile/account"
        exit 1
    fi
    
    ping -c 2 "$GITLAB_URL" 2>>/dev/null 1>&2 || (echo -e "$GITLAB_URL ${RED} Unrechable ${NC}" && exit 1) || exit 1
    
}


function getData(){
    
    local online=$(curl -s "https://${GITLAB_URL}/api/v3/projects?private_token=$GITLAB_PRIVATE_TOKEN&search=$PROJECT_SEARCH_PARAM&per_page=999&sort=asc&order_by=name" \
    | jq --raw-output --compact-output ".[]  | { "name": .name, "path": .path, "git": .ssh_url_to_repo }") || (echo "Can't fetch data" && exit 1)
    
    formatData "$online"
}


function formatData(){

    local online="$1"
    i=1
    echo "$online" | while read line;do
        
        git="$(echo $line | jq -r ".git")"
        echo -e "$i) git clone --progress --recursive --verbose $git ;;" >> "$gitlabGit"
        
        name="$(echo $line | jq -r ".name")"
        local projects_names=$(echo $i" "\""$name"\" "off" >> "$gitlabNames")
        
        i=$[i+1]

    done
}


function createGui(){
    
    local projects_names="$(cat $gitlabNames)"
    
cat >> "$gitlabScript" <<- EndOfScript
#!/bin/bash

# Janusz Ładecki <szunaj13pl@gmail.com>
# 21.09.2017

echo $i

function measureScreen(){
    rows=$(tput lines)
    cols=$(tput cols)
}

function createGui(){
    local TYPE="checklist"
    local HEIGHT=\$rows
    local WIDTH=\$(( cols / 2))
    local CHOICE_HEIGHT=\$(( rows - 4))
    local BACKTITLE="GitLab"
    local TITLE="GitLab"
    local MENU="Choose repo to clone:"


    local OPTIONS=($(cat $gitlabNames))

        local CHOICES=\$(dialog  --separate-output --checklist   \
                "\$MENU" \
                \$HEIGHT \$WIDTH \$CHOICE_HEIGHT \
                "\${OPTIONS[@]}" \
                2>&1 >/dev/tty)

    clear

    for choice in \$CHOICES
    do
        case \$choice in

EndOfScript
    
    # Insert git clone commands
    cat "$gitlabGit" >> "$gitlabScript"
    # Apend closing for 'for, case, function'
    echo -e "\n\t esac \n done \n} \n measureScreen \n createGui" >> "$gitlabScript"
    
}


function run(){
    # less "$gitlabScript"
    chmod +x "$gitlabScript"
    "$gitlabScript"
}


# Defines variables and create temp files
initial

# Install requierd programs
isInstalled curl git jq dialog

# Check if all variables ar defined and server is online
preRunCheck

# Request data and format data
getData

# Display results list of repositories
createGui

# Add premissions to execute and run script
run

# Cleaning
rm -f "$gitlabNames" "$gitlabGit" "$gitlabScript"
